### ISSUE TITLE
clean data on python notebook for ks-projects-201801.csv

### ISSUE THREAD

**Issue by juzcho** [Best-Brain-Gang/Crowdfunding_Analysis#12]

**Comment by n8patterson** [comment]
Use the ks-projects-201801.csv for now.

- Dropped the usdpledged col in favor of usd_pledged_real.
- Cleaned up launched and deadline cols by using to_datetime()
- Drop everything in state column except for successful and failed
- Rename successful -> 1 and failed -> 0 to match indiegogo
-  Sometimes projects are successful with no backers. Remove this data
- Remove all countries with that have euro currency and country equal to N,0"
- Create a dictionary of country and currency pairs to fix other N,0" countries to right country

Need to do:

- Make main_category match indiegogo main_categories
- Make currency matach indiegogo currency
- Make country match indiegogo country
