### ISSUE TITLE
Research a new Python library not previously covered in the course.

### ISSUE THREAD

**Issue by juzcho** [Best-Brain-Gang/Crowdfunding_Analysis#15]
Major Requirement for the Project.

**Comment by juzcho** [comment]
folium: https://python-visualization.github.io/folium/quickstart.html

**Comment by juzcho** [comment]
.

**Comment by Narwhilian** [comment]
The stats models library seems like it has a lot of potential to me. here is the link with the write up and functions, not all of them would be applicable seeing as we arent doing something time series related but some of them look pretty promising to me 

https://www.statsmodels.org/stable/index.html

**Comment by n8patterson** [comment]
This is related to #9, so closing #9 in favor of this.

https://mode.com/blog/python-data-visualization-libraries/

**Comment by n8patterson** [comment]
If you guys want to use the small kickstarter datasets. I will need to use the fixer.io API to convert the money cols to USD based to match our other dfs. So I will import and use a fixer.io package with:

`pip install fixerio`

`easy_install fixerio`

`from fixerio import Fixerio`

Link for reference:

https://fixerio.readthedocs.io/en/latest/
https://fixer.io/documentation

**Comment by n8patterson** [comment]
Papermill to seperate code:
https://papermill.readthedocs.io/en/latest/usage-execute.html

**Comment by n8patterson** [comment]
Ended up not using fixer.io. It does not really make sense to use on the small kickstarter data because we don't have any launched or deadline dates.

**Comment by n8patterson** [comment]
Adding viz libs to close this issue. Here is a link of what I added.
https://towardsdatascience.com/top-6-python-libraries-for-visualization-which-one-to-use-fe43381cd658

Each graphs different things better. Look at the related sites to see which one you want to use. We can remove whatever we don't use later.

For each do the following to your dev env. @cdhendy @juzcho We should add the below to the readme later.

Seaborn: `conda install seaborn`
Altair: `conda install -c conda-forge altair`
Bokeh: `conda install bokeh`
Folium: `conda install folium -c conda-forge`
