### ISSUE TITLE
Discuss what is our User Story i.e features we want to be able to make.

### ISSUE THREAD

**Issue by juzcho** [Best-Brain-Gang/Crowdfunding_Analysis#16]

**Comment by cdhendy** [comment]
How should the end user use this notebook - first for data analysis and then to determine what platform is best for their project

**Comment by n8patterson** [comment]
> How should the end user use this notebook - first for data analysis and then to determine what platform is best for their project

#46 issue is related.

**Comment by n8patterson** [comment]
Closing this as we have made issues and flushed them all out during out zoom meetings.
