### ISSUE TITLE
Change profile picture for best brain gang organization on github

### ISSUE THREAD

**Issue by cdhendy** [Best-Brain-Gang/Crowdfunding_Analysis#17]

**Comment by n8patterson** [comment]
hahah.......really....critical....

**Comment by juzcho** [comment]
I can overwrite this "CRITICAL" tag lol

**Comment by cdhendy** [comment]
![depositphotos_68608585-stock-illustration-human-brain](https://user-images.githubusercontent.com/82166077/125885076-a02eddcc-f9d9-4e24-9d83-5c756e16cdf9.jpg)
![9-95311_15-cartoon-brain-png-for-free-on-mbtskoudsalg](https://user-images.githubusercontent.com/82166077/125885079-4b5e2683-34ec-44bb-9fd4-93df4c545d41.png)
![61-617632_brain-outline-png-png-black-and-white-library](https://user-images.githubusercontent.com/82166077/125885081-2c3a3ff9-1b07-4fdc-ab8f-352768eb1a79.png)

Some choices for us

**Comment by n8patterson** [comment]
@juzcho Plz choose which picture you want and update org picture as you are the owner, so we can close this.
