### ISSUE TITLE
Make main_category col match across df

### ISSUE THREAD

**Issue by n8patterson** [Best-Brain-Gang/Crowdfunding_Analysis#55]
Large kickstarter dataset is most restrictive so will match all other dfs to that.

**Comment by n8patterson** [comment]
Kickstarter large categories:

- 'Publishing'
- 'Film & Video'
- 'Music'
- 'Food'
- 'Crafts'
- 'Games'
- 'Design'
- 'Comics'
- 'Fashion'
- 'Theater'
- 'Art'
- 'Photography'
- 'Technology'
- 'Dance'
- 'Journalism'

**Comment by n8patterson** [comment]
Indiegogo categories:

- 'Transportation' :  'Technology',
- 'Human Rights' : 'Journalism',
- 'Photography' : 'Photography',
- 'Camera Gear' : 'Film & Video',
- 'Wellness' : 'Food',
- 'Productivity' : 'Technology',
- 'Audio' : 'Technology',
- 'Tabletop Games' : Games',
- 'Energy & Green Tech' : 'Technology',
- 'Podcasts, Blogs & Vlogs' : 'Journalism',
- 'Culture' : 'Art',
- 'Fashion & Wearables' : 'Technology',
- 'Local Businesses' : 'Journalism', -> Delete
- 'Phones & Accessories' : 'Technology',
- 'Dance & Theater' : 'Theater',
- 'Environment' : 'Design', -> Delete
- 'Video Games' : 'Games',
- 'Home' : 'Crafts', -> Delete
- 'Music' : 'Music',
- 'Health & Fitness' : 'Food',
- 'Education' : 'Technology', - Delete
- 'Art' : 'Art',
- 'Writing & Publishing' : 'Journalism',
- 'Comics' : 'Art',
- 'Food & Beverages' : 'Food',
- 'Travel & Outdoors' : 'Photography', - Delete
- 'Film' : 'Film & Video',
- 'Web Series & TV Shows' : 'Film & Video'

**Comment by n8patterson** [comment]
Kickstarter small categories:

- 'Tabletop Games'
- 'Product Design'
- 'Web'
- 'Narrative Film'
- 'Video Games'
- 'Gaming Hardware'
- 'Television'
- 'Hardware'
- 'Music'
- 'Space Exploration'
- 'Radio &amp; Podcasts'
- 'Flight'
- 'Technology'
- 'Sound'
- 'Animation'
- 'Games'
- 'Action'
- 'Gadgets'
- 'Documentary'
- '3D Printing'
- 'DIY Electronics'
- 'Publishing'
- 'Fashion'
- 'Comics'
- 'Typography'
- 'Children's Books'
- 'Apparel'
- 'Food'
- 'Crafts'
- 'Camera Equipment'
- 'Comedy'
- 'Design'
- 'Graphic Design'
- 'Apps'
- 'Hip-Hop'
- 'World Music'
- 'Film &amp; Video'
- 'Drinks'
- 'Wearables'
- 'Accessories'
- 'Footwear'
- 'Science Fiction'
- 'Nonfiction'
- 'Robots'
- 'Software'
- 'Chiptune'
- 'Webseries'
- 'Webcomics'
- 'Rock'
- 'Playing Cards',
- 'Cookbooks'
- 'Fantasy'
- 'Photography'
- 'Anthologies'
- 'Faith'
- 'Mixed Media'
- 'Art'
- 'Metal'
- 'Small Batch'
- 'Classical Music'
- 'Architecture'
- 'Pop'
- 'Dance'
- 'Electronic Music'
- 'Art Books'
- 'Graphic Novels'
- 'Musical'
- 'Theater'
- 'Photobooks'
- 'Drama'
- 'Shorts'
- 'Ready-to-wear'
- 'Indie Rock'
- 'Civic Design'
- 'Childrenswear'
- 'Print'
- 'Horror'
- 'Periodicals'
- 'Sculpture'
- 'Comic Books'
- 'People'
- 'Puzzles'
- 'Public Art'
- 'Illustration'
- 'Mobile Games'
- 'Restaurants'
- 'Literary Journals'
- 'Movie Theaters'
- 'Country &amp; Folk'
- 'Fiction'
- 'Journalism'
- 'Thrillers'
- 'Audio'
- 'Vegan'
- 'Fabrication Tools'
- 'Food Trucks'
- 'Spaces'
- 'Family'
- 'Music Videos'
- 'Painting'
- 'Academic'
- 'Poetry'
- 'Interactive Design'
- 'Romance'
- 'Stationery'
- 'Jazz'
- 'Photo'
- 'Installations'
- 'Video'
- 'Calendars'
- 'Zines'
- 'Conceptual Art'
- 'Digital Art'
- 'Jewelry'

**Comment by juzcho** [comment]
yes I think this should be done. so both kickstarter and indiegogo should have same main category at least. So we can do a side-by-side plotting.
