### ISSUE TITLE
get Geocoding API to get latitude and longitude

### ISSUE THREAD

**Issue by juzcho** [Best-Brain-Gang/Crowdfunding_Analysis#66]
[https://developer.mapquest.com/documentation/open/geocoding-api/](url)

[https://developers.google.com/maps/documentation/geocoding/get-api-key](url)

**Comment by n8patterson** [comment]
CSV:
https://developers.google.com/public-data/docs/canonical/countries_csv

**Comment by n8patterson** [comment]
PR #73 fixed this.
